import pandas as pd
df = pd.read_csv("attendance.csv")
print("===== Original Dataset =====")
print(df.head())
print("\n===== Dataset Information =====")
print(df.info())
print("\n===== Shape of Dataset =====")
print(df.shape)
print("\n===== Missing Values =====")
print(df.isnull().sum())
df = df.drop_duplicates()
df["Attendance"] = df["Attendance"].fillna("Absent")
print("\n===== Cleaned Dataset =====")
print(df)
df.to_csv("cleaned_attendance.csv", index=False)
print("\nDataset cleaned successfully!")